### PR TITLE
19 transition to twin macro

### PR DESCRIPTION
**Pull request by kev1n80**
Transitioned from Tailwind to Twin. 
- In the process I updated the fonts to mimic the fonts Diez captured from Figma .
image
- Multi Select will now bold items that have been selected 
image

### CODE REVIEW

**Comment by Jose-S** [comment]
Hey, for some reason when I pull all the changes to my machine, I get the error "Couldn’t resolve Tailwind class name: fontStyle-5." Which means that for some reason the tailwind font classes are not loading. Lmk if it works in your machine!

**Comment by Jose-S** [comment]
Files under Screen folder have not been transitioned to Twin.

**Comment by kev1n80** [comment]
> Files under Screen folder have not been transitioned to Twin.

Fixed the bug, and the all files using inline CSS now uses Twin prop.

**Comment by sophiacrennan** [comment]
When I try running this branch, a blank page opens up. The console log has a few errors such as `Sidebar.js:81 Uncaught TypeError: Cannot read property 'breakpoints' of null` and ```
useMediaQuery.js:21 Material-UI: The `query` argument provided is invalid.
You are providing a function without a theme in the context.
One of the parent elements needs to use a ThemeProvider. 
``` Do you also get these errors or is it just me?

**Comment by kev1n80** [comment]
> When I try running this branch, a blank page opens up. The console log has a few errors such as `Sidebar.js:81 Uncaught TypeError: Cannot read property 'breakpoints' of null` and `useMediaQuery.js:21 Material-UI: The`query`argument provided is invalid. You are providing a function without a theme in the context. One of the parent elements needs to use a ThemeProvider. ` Do you also get these errors or is it just me?

:( unfortunately I do not get any of those errors.

**Comment by Jose-S** [comment]
Yeah I get the same error. Let me try to fix it and then hopefully be able to merge with #47 and remove Diez library.

**Comment by Jose-S** [comment]
The latest version(v5) of Material UI Library had been added to package.json. This new version includes a lot of breaking changes. These are two of the changes that caused the error:
- Theme breakpoints for responsive components were updated [More Info](https://next.material-ui.com/guides/migration-v4/#theme)
- The ExpansionPanel Component had been renamed to Accordion [More Info](https://next.material-ui.com/guides/migration-v4/#expansionpanel)

**I plan to Merge this branch with #47, that should fix our font issue that this branch has.** After all branches have been merged and Diez has been removed I would like to update Material UI V5 (depends if React Admin supports it).

Let me know if the App runs in y'alls computer.

**Review by Jose-S — APPROVED** [review]
Thank you!

Looks nice, consistent styling approach! I think after we merge with #47 we can start resolving issues I'm having with removing Diez.

**Comment by sophiacrennan** [comment]
Awesome thanks @Jose-S! It works on my computer and everything looks good @kev1n80!

**Review by sophiacrennan — APPROVED** [review]

**Pull request merged**
