### PR TITLE
74 add student exams

### PR DESCRIPTION
**Pull request by emaela**
Added student exams into the student details page

### CODE REVIEW

**Comment by sophiacrennan** [comment]
in the exam list, there are no course names under the course title and there is no title for letter grades

**Comment by emaela** [comment]
Oh that may be because the corresponding changes in the backend (adding
courses to exams/student exams) hasn’t been merged to dev yet

**Comment by emaela** [comment]
> in the exam list, there are no course names under the course title and there is no title for letter grades

I just merged the corresponding backend changes into dev, so the course info should show up if you pull the backend. 
I removed the letter grade column title to match the figma mockups, but I could add it back in.

**Comment by sophiacrennan** [comment]
That makes sense. Now the courses show up for me. Keep it as the mockups. I didn't know about that haha

**Review by sophiacrennan — APPROVED** [review]

**Pull request merged**
