### PR TITLE
71 styling studentcourse student pages

### PR DESCRIPTION
**Pull request by emaela**

### CODE REVIEW

**Review by sophiacrennan — APPROVED** [review]
Styling looks good!!

**Comment by sophiacrennan** [comment]
I'm not sure what the mockups look like but I feel like the courses tab should come before the exam tab?

**Comment by sophiacrennan** [comment]
Ok I looked at the mockups and I see that the old design had the assessments tab before the courses tab. But I still think that courses should go first...what do you think? Feel free to respond tomorrow haha

**Comment by emaela** [comment]
I agree, I'll make the courses tab go first.

**Pull request merged**
